name: Update share price files

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 3 * * *' # Scheduled trigger at 3 AM UTC daily

jobs:
  run-scheduled-task:
    name: Create share price files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stock_symbol: ['MSFT', 'META']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update_share_price_files.py script
      run: python update_share_price.py ${{ secrets.TWELVE_DATA_API_KEY }} ${{ matrix.stock_symbol }}

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch
        git add ${{ matrix.stock_symbol }}.json
        git commit -m "Update share ${{ matrix.stock_symbol }} price file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}